[package]
name = "hah"
version = "0.0.1"
authors = ["William Clarke <wmmclarke@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.1"
